# Generated by Django 2.1.4 on 2018-12-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Subscribers',
        ),
    ]
