# Generated by Django 2.1.4 on 2018-12-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20181209_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Мой Саб', 'verbose_name_plural': 'Моя армия сабов'},
        ),
    ]
